AppBundle\Entity\Stagiaire:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\StagiaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
        firstname:
            type: string
            length: '255'
        birthday:
            type: datetime
        email:
            type: string
            length: '255'
        phone:
            type: string
            length: '10'
        pcode:
            type: string
            length: '5'

    manyToMany:
        competences:
            targetEntity: Competence
            inversedBy: stagiaires

    lifecycleCallbacks: {  }
